. Clone a local copy of the Quick Start templates (including all of its submodules). From the command line, run:
+
----
git clone --recurse-submodules https://github.com/aws-quickstart/quickstart-atlassian-bitbucket.git
----
. *(Optional)* The Quick Start templates repository uses the directory structure required by the Quick Start interface. If needed (for example, to minimize storage costs), you can remove all other files except the following:
+
----
quickstart-atlassian-bitbucket
├── submodules
├── quickstart-atlassian-services
│   └── templates
│       └── quickstart-vpc-for-atlassian-services.yaml
└── templates
    ├── quickstart-bitbucket-dc-with-vpc.template.yaml
    └── quickstart-bitbucket-dc.template.yaml
----
. Install and set up the https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html[AWS Command Line Interface (CLI)] so that you can create an S3 bucket and upload content to it.
. Create an S3 bucket in your Region:
+
----
aws s3 mb s3://<BUCKET_NAME> --region <AWS_REGION>
----
. Choose which Quick Start template to use:
** `quickstart-bitbucket-master-with-vpc.template.yaml`: Use this template for deploying {partner-product-name-short} into a new ASI (end-to-end deployment).
+
** `quickstart-bitbucket.template.yaml`: Use this template for deploying {partner-product-name-short} into an existing ASI.
. In both templates, the `QSS3BucketName` default value is set to `aws-quickstart`. Replace this value with the name of the bucket you created earlier (`<BUCKET_NAME>`).
. Return to the parent directory of your local clone of the Quick Start templates. From there, upload all the files in your local clone to your S3 bucket:
+
----
aws s3 cp quickstart-atlassian-bitbucket s3://<BUCKET_NAME> --recursive --acl public-read
----
